# frontend/Dockerfile

# --- STAGE 1: BUILDER ---
# Install dependencies and build the app
FROM node:24-alpine AS builder
WORKDIR /app

# Define Argument 
ARG NEXT_PUBLIC_API_URL

# Set it as an Environment Variable for the build command
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

# Copy package files first (better caching)
COPY package*.json ./
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the Next.js app
# This creates the .next/standalone folder
RUN npm run build

# --- STAGE 2: RUNNER ---
# Create a small, clean image for production
FROM node:24-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# 1. CRITICAL: Force the server to listen on 0.0.0.0
# Without this, it defaults to localhost and Render gets a 502
ENV HOSTNAME="0.0.0.0"

# 2. Let Render set the PORT, but default to 3000 if missing
# Note: Render automatically injects a PORT env var (usually 10000)
ENV PORT=3000

# COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Exposed port must match the fallback
EXPOSE 3000

CMD ["node", "server.js"]